const offers = {
  'growth-marketing-strategy': ['What We Offer', 'Growth & Marketing Strategy', 'Seasoned VP- and C-level growth strategists help you plan for the long term and turn ambitious goals into a clear, executable growth system.', ['Growth strategy and planning', 'Executive marketing leadership', 'Market and channel prioritization']],
  'ai-services': ['What We Offer', 'AI Services', 'Turn AI ambition into marketing workflows your team will actually use, from strategic guidance through implementation and enablement.', ['AI opportunity assessment', 'Workflow and automation design', 'Team enablement and adoption']],
  'paid-social': ['What We Offer', 'Paid Social', 'Build efficient paid social programs with sharper creative, better audience signals, and measurement you can trust.', ['Audience and creative strategy', 'Campaign activation and testing', 'Performance reporting']],
  'paid-search': ['What We Offer', 'Paid Search', 'Capture high-intent demand with search programs built around commercial goals, landing-page relevance, and disciplined optimization.', ['Search strategy and account structure', 'Keyword and ad development', 'Budget and bid optimization']],
  'b2b-advertising': ['What We Offer', 'B2B Advertising', 'Create a dependable pipeline engine that reaches the right buyers across a considered B2B journey.', ['Account and audience targeting', 'Demand generation campaigns', 'Lead quality measurement']],
  'affiliate-marketing': ['What We Offer', 'Affiliate Partnerships', 'Extend your reach through a partner ecosystem aligned to your brand, audience, and commercial model.', ['Partner program strategy', 'Recruitment and enablement', 'Attribution and optimization']],
  'seo': ['What We Offer', 'Search Engine Optimization', 'Earn durable visibility with a technical, content, and measurement foundation built around search intent.', ['Technical SEO and site health', 'Content and search intent mapping', 'Authority and performance growth']],
  'geo': ['What We Offer', 'Generative Engine Optimization', 'Make your brand easier for modern answer engines to understand, surface, and cite.', ['Entity and schema architecture', 'Semantic authority mapping', 'AI search visibility measurement']],
  'product-marketing': ['What We Offer', 'Product Marketing', 'Clarify your product story and connect positioning to the audiences and channels that drive adoption.', ['Positioning and messaging', 'Launch and campaign planning', 'Sales enablement']],
  'product-led-growth': ['What We Offer', 'Product-Led Growth', 'Design a growth loop where product value creates activation, retention, and sustainable expansion.', ['Activation journey design', 'Lifecycle experiments', 'Retention and expansion strategy']],
  'podcast-radio-tv': ['What We Offer', 'Podcast, Radio, TV', 'Bring your brand to high-attention channels with creative and measurement designed for real-world reach.', ['Channel and audience planning', 'Creative development', 'Reach and response measurement']],
  'amazon-marketing': ['What We Offer', 'Amazon Marketing', 'Improve discoverability and conversion across the Amazon marketplace with a disciplined retail growth plan.', ['Retail search strategy', 'Listing and creative optimization', 'Marketplace performance tracking']],
  'ecommerce-marketplaces': ['What We Offer', 'Ecommerce Marketplaces', 'Build marketplace momentum with a clear merchandising, acquisition, and retention system.', ['Marketplace expansion planning', 'Catalog and conversion optimization', 'Performance media']],
  'content-marketing': ['What We Offer', 'Content Marketing', 'Create useful, distinctive content that earns attention and moves the right audience toward action.', ['Editorial strategy', 'Content production systems', 'Distribution and measurement']],
  'social-media-community': ['What We Offer', 'Social Media & Community', 'Build an active brand presence through consistent storytelling, conversation, and community value.', ['Social strategy and planning', 'Content and engagement', 'Community insight loops']],
  'influencer-creator-marketing': ['What We Offer', 'Influencer & Creator Marketing', 'Partner with credible voices to turn cultural relevance into measurable brand and demand growth.', ['Creator identification and fit', 'Campaign and collaboration design', 'Performance measurement']],
  'lifecycle-marketing': ['What We Offer', 'Lifecycle Marketing', 'Guide customers from first signal to lasting value with relevant, timely, and measurable communication.', ['Lifecycle journey mapping', 'Email and CRM programs', 'Retention and expansion']],
  'cro': ['What We Offer', 'Conversion Rate Optimization', 'Turn more qualified traffic into action through evidence-led experimentation across the funnel.', ['Funnel diagnosis', 'Experiment design and testing', 'Conversion insight reporting']],
  'direct-mail': ['What We Offer', 'Direct Mail', 'Give high-value audiences a memorable physical touchpoint that complements your digital growth system.', ['Audience and offer strategy', 'Campaign production', 'Response measurement']],
  'creative-services': ['What We Offer', 'Creative Services', 'Develop distinctive creative that makes your positioning clear and gives every channel more to work with.', ['Creative direction', 'Campaign and brand assets', 'Creative testing']],
  'analytics-attribution': ['What We Offer', 'Analytics & Attribution', 'Replace fragmented reporting with a clear view of what creates demand, conversion, and profitable growth.', ['Measurement architecture', 'Attribution and dashboards', 'Decision-ready insights']],
  'marketing-operations': ['What We Offer', 'Marketing Operations', 'Connect the people, processes, data, and systems that make marketing easier to scale.', ['Process and systems design', 'CRM and workflow integration', 'Governance and enablement']],
  'all-capabilities': ['What We Offer', 'All Capabilities', 'Bring the right combination of strategy, creative, media, technology, and measurement together around your growth objective.', ['Growth strategy', 'Demand and lifecycle programs', 'Measurement and optimization']],
  'early-stage': ['Who We Work With', 'Early Stage', 'Build a practical foundation for finding product-market fit, creating demand, and learning quickly.', ['Positioning and first channels', 'Lean acquisition systems', 'Measurement foundations']],
  'high-growth': ['Who We Work With', 'High Growth', 'Turn momentum into a repeatable growth system without losing the speed that got you here.', ['Channel scaling', 'Conversion and retention', 'Growth operating rhythm']],
  'enterprise': ['Who We Work With', 'Enterprise', 'Coordinate complex teams, markets, and systems around growth that is measurable and durable.', ['Portfolio and market alignment', 'Marketing systems and governance', 'Executive reporting']],
  'investors': ['Who We Work With', 'Investors', 'Support portfolio companies with repeatable growth insight, strategic clarity, and execution capacity.', ['Portfolio growth diagnostics', 'Shared playbooks and benchmarks', 'Embedded growth support']],
  'freelancers': ['Ways to Engage', 'Freelancers', 'Add senior growth strategy and specialist execution when your project needs more range or momentum.', ['Specialist strategy support', 'Campaign and funnel execution', 'Flexible project collaboration']],
  'agency-teams': ['Ways to Engage', 'Agency Teams', 'Extend your team with technical growth capability that fits your client delivery model.', ['White-label strategy support', 'Specialist delivery capacity', 'Measurement and reporting']],
  'full-time-employees': ['Ways to Engage', 'Full-Time Employees', 'Build a stronger internal growth function with the systems, insight, and hands-on support to move faster.', ['Team structure and planning', 'Capability building', 'Embedded execution']],
  'advisors': ['Ways to Engage', 'Advisors', 'Give your clients or portfolio companies an experienced growth partner for complex marketing decisions.', ['Growth assessment', 'Strategic advisory', 'Execution roadmaps']]
};

const slug = new URLSearchParams(window.location.search).get('offer') || 'all-capabilities';
const offer = offers[slug] || offers['all-capabilities'];
document.title = `Fluvo — ${offer[1]}`;
document.getElementById('offerCategory').textContent = offer[0];
document.getElementById('offerEyebrow').textContent = offer[0].toUpperCase();
document.getElementById('offerTitle').textContent = offer[1];
document.getElementById('offerIntro').textContent = offer[2];
document.getElementById('offerDetails').innerHTML = offer[3].map((item, index) => `<article class="offer-detail"><h3>${String(index + 1).padStart(2, '0')} / ${item}</h3><p>Designed around your goals, this work creates a clearer path from insight to action and gives your team a practical way to measure progress.</p></article>`).join('');
