-- =============================================================================
-- FLUVO SUPABASE ROW LEVEL SECURITY (RLS) & SCHEMA SETUP
-- Run this script once in your Supabase Project: SQL Editor -> New Query -> Run
-- =============================================================================

-- 1. Ensure the inquiries table exists with complete schema
CREATE TABLE IF NOT EXISTS public.queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT DEFAULT 'schedule',
  full_name TEXT NOT NULL,
  work_email TEXT NOT NULL,
  phone TEXT,
  company TEXT,
  ad_spend TEXT DEFAULT 'N/A',
  preferred_date TEXT,
  preferred_time TEXT,
  message TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'in-progress', 'resolved')),
  starred BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMPTZ
);

-- 2. Create performance indexes
CREATE INDEX IF NOT EXISTS idx_queries_status ON public.queries(status);
CREATE INDEX IF NOT EXISTS idx_queries_created_at ON public.queries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_queries_work_email ON public.queries(work_email);

-- 3. Enable Row Level Security (RLS)
-- This is critical: without RLS, any person with the anon key can read all inquiries.
ALTER TABLE public.queries ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any existing insecure policies
DROP POLICY IF EXISTS "Allow anon insert only" ON public.queries;
DROP POLICY IF EXISTS "Allow public insert" ON public.queries;
DROP POLICY IF EXISTS "Public can select queries" ON public.queries;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.queries;
DROP POLICY IF EXISTS "Enable all access for anon" ON public.queries;
DROP POLICY IF EXISTS "Enable insert for anon only" ON public.queries;

-- 5. Policy: Anonymous public users (anon key) can ONLY INSERT new inquiries
-- They CANNOT SELECT, UPDATE, or DELETE any records.
CREATE POLICY "Allow anon insert only"
ON public.queries
FOR INSERT
TO anon
WITH CHECK (true);

-- 6. Note on Service Role Key:
-- The server-side Admin and Website serverless functions use SUPABASE_SERVICE_ROLE_KEY.
-- The service_role key automatically bypasses RLS in Supabase, allowing full
-- authenticated management without exposing reading rights to the public web.
