export const caseStudies = [
  {
    id: 'aurawear',
    company: 'AURAWEAR',
    location: 'Mumbai, India',
    country: 'India',
    region: 'india',
    industry: 'D2C / Fashion & Lifestyle',
    engagement: 'Full-Funnel Growth Architecture',
    challenge: 'Fragmented acquisition, weak lifecycle automation and limited visibility into customer behaviour were restricting efficient growth.',
    strategy: 'Build a connected acquisition and retention architecture combining audience intelligence, performance marketing, CRM automation and conversion optimization.',
    implementation: ['Technical SEO', 'Paid Media', 'Audience Segmentation', 'CRM Automation', 'Lifecycle Workflows', 'CRO', 'GA4 Attribution'],
    capabilities: ['SEO & GEO', 'PAID MEDIA', 'AUDIENCE SEGMENTATION', 'CRM AUTOMATION', 'CRO', 'GA4'],
    metrics: [
      { value: '+42%', label: 'Repeat Purchase Rate' },
      { value: '+31%', label: 'Email CTR' },
      { value: '-27%', label: 'Cart Abandonment' },
      { value: '3.4x', label: 'Blended Campaign ROI' }
    ],
    outcome: 'A connected acquisition and retention system with clearer customer intelligence and stronger commercial efficiency.',
    testimonial: 'Fluvo helped us move from disconnected campaigns to a much more intelligent growth system. We gained significantly better visibility into what was driving customer engagement.',
    person: 'Priya Sharma',
    role: 'Growth Lead',
    services: ['Technical SEO', 'Paid Media', 'Audience Segmentation', 'CRM Automation', 'Lifecycle Workflows', 'CRO', 'GA4 Attribution'],
    featured: true
  },
  {
    id: 'nexora-cloud',
    company: 'NEXORA CLOUD',
    location: 'Bengaluru, India',
    country: 'India',
    region: 'india',
    industry: 'B2B SaaS',
    engagement: 'Demand Generation & Conversion Engineering',
    challenge: 'High website traffic and trial volume were not translating efficiently into activated and paying users.',
    strategy: 'Connect acquisition data, product engagement signals and conversion journeys into a unified funnel.',
    implementation: ['Technical SEO', 'High-Performance Landing Pages', 'Audience Segmentation', 'CRM Workflow Automation', 'Conversion Rate Optimization', 'GA4 Event Architecture'],
    capabilities: ['SEO & GEO', 'WEB ENGINEERING', 'AUDIENCE SEGMENTATION', 'CRM AUTOMATION', 'CRO', 'GA4'],
    metrics: [{ value: '+38%', label: 'Trial-to-Paid Conversion' }, { value: '+52%', label: 'User Activation' }, { value: '-34%', label: 'Churn Risk' }, { value: '2.8x', label: 'Engagement' }],
    outcome: 'A unified funnel that connected intent, activation signals and conversion journeys.',
    testimonial: 'Fluvo gave our growth team a much clearer picture of customer intent and where intervention would have the highest impact.',
    person: 'Arjun Mehta',
    role: 'Head of Growth',
    services: ['Technical SEO', 'Web Engineering', 'Audience Segmentation', 'CRM Automation', 'CRO', 'GA4'],
    featured: false
  },
  {
    id: 'mint-moss',
    company: 'MINT & MOSS',
    location: 'New Delhi, India',
    country: 'India',
    region: 'india',
    industry: 'Beauty & Consumer',
    engagement: 'Audience Intelligence & Lifecycle Growth',
    challenge: 'Strong traffic and acquisition activity were not translating into sufficient repeat revenue.',
    strategy: 'Use behavioural segmentation and lifecycle automation to create more relevant customer journeys.',
    implementation: ['Audience Intelligence', 'CRM Segmentation', 'Lifecycle Marketing', 'Personalization', 'Retargeting', 'CRO'],
    capabilities: ['AUDIENCE SEGMENTATION', 'CRM AUTOMATION', 'LIFECYCLE MARKETING', 'PAID MEDIA', 'CRO'],
    metrics: [{ value: '+46%', label: 'Repeat Revenue' }, { value: '+29%', label: 'Conversion Rate' }, { value: '+41%', label: 'Engagement' }, { value: '-22%', label: 'Customer Drop-Off' }],
    outcome: 'More relevant lifecycle journeys that turned existing demand into repeat revenue.',
    testimonial: 'The biggest improvement was how relevant our customer communication became. The entire lifecycle felt more connected.',
    person: 'Rhea Kapoor',
    role: 'CRM Manager',
    services: ['Audience Segmentation', 'CRM Automation', 'Lifecycle Marketing', 'Paid Media', 'CRO'],
    featured: false
  },
  {
    id: 'northstar-fitness',
    company: 'NORTHSTAR FITNESS',
    location: 'London, United Kingdom',
    country: 'United Kingdom',
    region: 'international',
    industry: 'Fitness & Wellness Technology',
    engagement: 'Lifecycle Retention System',
    challenge: 'A growing inactive customer segment was creating significant untapped revenue potential.',
    strategy: 'Identify behavioural drop-off signals and trigger automated win-back journeys.',
    implementation: ['Customer Segmentation', 'Engagement Scoring', 'Lifecycle Automation', 'Behaviour Triggers', 'CRM Workflows', 'Retention Optimization'],
    capabilities: ['AUDIENCE SEGMENTATION', 'CRM AUTOMATION', 'LIFECYCLE MARKETING', 'CRO'],
    metrics: [{ value: '+37%', label: 'Reactivation' }, { value: '+44%', label: 'Engagement' }, { value: '+26%', label: 'Returning Users' }, { value: '3.1x', label: 'Campaign Efficiency' }],
    outcome: 'A systematic retention loop that identified drop-off and brought customers back into the journey.',
    testimonial: 'Fluvo helped us identify where customers were dropping out of the journey and build a much more systematic way to bring them back.',
    person: 'James Wilson',
    role: 'Customer Growth Manager',
    services: ['Audience Segmentation', 'CRM Automation', 'Lifecycle Marketing', 'CRO'],
    featured: false
  },
  {
    id: 'veloce-market',
    company: 'VELOCE MARKET',
    location: 'Dubai, UAE',
    country: 'UAE',
    region: 'international',
    industry: 'E-commerce Marketplace',
    engagement: 'Performance Marketing & Attribution',
    challenge: 'Multiple acquisition channels were producing fragmented performance data and inconsistent optimization decisions.',
    strategy: 'Connect audience segmentation, campaign performance and first-party measurement into a unified optimization framework.',
    implementation: ['Paid Media', 'Audience Segmentation', 'First-Party Attribution', 'GA4', 'Campaign Optimization', 'CRO'],
    capabilities: ['PAID MEDIA', 'FIRST-PARTY ATTRIBUTION', 'GA4', 'AUDIENCE SEGMENTATION', 'CRO'],
    metrics: [{ value: '+49%', label: 'Open Rate' }, { value: '+35%', label: 'CTR' }, { value: '+28%', label: 'Conversion' }, { value: '-19%', label: 'Acquisition Cost' }],
    outcome: 'A first-party measurement framework that clarified which audiences were creating commercial value.',
    testimonial: 'Fluvo gave us a much clearer understanding of which audiences and campaigns were actually creating commercial value.',
    person: 'Omar Hassan',
    role: 'Marketing Director',
    services: ['Paid Media', 'First-Party Attribution', 'GA4', 'Audience Segmentation', 'CRO'],
    featured: false
  },
  {
    id: 'lumenpay',
    company: 'LUMENPAY',
    location: 'Singapore',
    country: 'Singapore',
    region: 'international',
    industry: 'Fintech',
    engagement: 'Acquisition-to-Activation Growth System',
    challenge: 'Customer acquisition was strong, but activation and lifecycle engagement required a more connected operating model.',
    strategy: 'Engineer an integrated acquisition, onboarding and lifecycle framework.',
    implementation: ['Paid Acquisition', 'Landing Page Optimization', 'CRM Automation', 'Customer Segmentation', 'GA4', 'Lifecycle Workflows', 'Conversion Optimization'],
    capabilities: ['PAID MEDIA', 'WEB ENGINEERING', 'CRM AUTOMATION', 'AUDIENCE SEGMENTATION', 'GA4', 'CRO'],
    metrics: [{ value: '+33%', label: 'Activation' }, { value: '+47%', label: 'Engagement' }, { value: '+24%', label: 'Conversion' }, { value: '-29%', label: 'Drop-Off' }],
    outcome: 'An integrated operating model connecting acquisition, onboarding and lifecycle engagement.',
    testimonial: 'Connecting customer behaviour with automated engagement gave our team an entirely new level of visibility.',
    person: 'Sofia Tan',
    role: 'Growth Manager',
    services: ['Paid Media', 'Web Engineering', 'CRM Automation', 'Audience Segmentation', 'GA4', 'CRO'],
    featured: false
  },
  {
    id: 'edvanta',
    company: 'EDVANTA',
    location: 'Toronto, Canada',
    country: 'Canada',
    region: 'international',
    industry: 'EdTech',
    engagement: 'Engagement & Conversion Optimization',
    challenge: 'Strong learner acquisition but declining engagement throughout the customer lifecycle.',
    strategy: 'Combine behavioural segmentation, automated journeys and conversion optimization.',
    implementation: ['Audience Segmentation', 'Engagement Scoring', 'CRM Automation', 'Lifecycle Marketing', 'Conversion Optimization', 'Analytics'],
    capabilities: ['AUDIENCE SEGMENTATION', 'CRM AUTOMATION', 'LIFECYCLE MARKETING', 'CRO', 'GA4'],
    metrics: [{ value: '+36%', label: 'Course Completion' }, { value: '+43%', label: 'Engagement' }, { value: '+25%', label: 'Returning Users' }, { value: '2.6x', label: 'Campaign Efficiency' }],
    outcome: 'Timely, relevant customer communication that improved engagement without increasing operational workload.',
    testimonial: 'Fluvo made our customer communication significantly more timely and relevant without increasing our operational workload.',
    person: 'Daniel Carter',
    role: 'Growth Director',
    services: ['Audience Segmentation', 'CRM Automation', 'Lifecycle Marketing', 'CRO', 'GA4'],
    featured: false
  }
];
